name: nextwave

services:
  db:
    image: mysql:8.0
    container_name: nextwave-db
    restart: always
    env_file:
      - ../env/.env.db
    volumes:
      - ../../services/db:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  api:
    build:
      context: ../../services/api
      dockerfile: Dockerfile
    container_name: nextwave-api
    restart: always
    env_file:
      - ../env/.env.api
    ports:
      - "8000:8000"
    volumes:
      - ../../services/api:/app
    depends_on:
      - db

  front:
    build:
      context: ../../services/front
      dockerfile: dockerfile
    container_name: nextwave-front
    ports:
      - "3000:3000"
    env_file:
      - ../env/.env.front
    # volumes:
    #   - ../../services/front:/workspace
    #   - /workspace/node_modules
    #   - /workspace/.next
    restart: always

  proxy:
    build:
      context: ../../services/proxy
      dockerfile: Dockerfile
    container_name: nextwave-proxy
    ports:
      - "80:80"
    depends_on:
      - api
      - front
    environment:
      - APP_ENV=production
    restart: always
